### ISSUE TITLE
Keyboard not fully displaying on Search Screen

### ISSUE THREAD

**Issue by ladybeitel** [Lambda-School-Labs/betterreads-ios#97]
Currently, the keyboard on iPhone 8 is not fully showing on the Search Results Screen.

Motivation
------------
As a user, I would like to see the full keyboard to type.

Finish Line
------------
User can be assured that the keyboard will fully appear when typing in a text field. 

<img width="559" alt="Screen_Shot_2020-05-01_at_6 31 12_PM" src="https://user-images.githubusercontent.com/18120418/83167353-25779800-a0de-11ea-9a51-ff64af18ad67.png">

**Comment by ladybeitel** [comment]
May be due to keyboard accessory bar, not the actual keyboard.

**Comment by alvare52** [comment]
tool bar removed entirely. That solves the issue
